# Nothing here yet because I haven't gotten the skew compiler to work yet

@import {
	def describe(desc string, func dynamic)
	def it(desc string, func dynamic)

	namespace console {
		const log dynamic
	}
}

@entry
def testMain {
	describe("thing", () => {
		describe("more", () => {
			it("huh", () => {
				var vc1 = VectorClock.new("site1")
				var vc2 = VectorClock.new("site2")
				vc1.currentTime <=> vc2.currentTime
			})
		})
	})
}

