# Nothing here yet because I haven't gotten the skew compiler to work yet

@import {
	def describe(desc string, func dynamic)
	def it(desc string, func dynamic)

	namespace console {
		const log dynamic
	}
}

@entry
def testMain {
	describe("VectorClock tests", () => {
		it("VectorClock.Time.get", () => {
			var vc = VectorClock.new("site1")
			assert(vc.currentTime.get("bogus site id") == 0)

			vc.tick
			assert(vc.currentTime.get("site1") == 1)
			assert(vc.currentTime.get("bogus site id") == 0)

			vc = VectorClock.new("site1", VectorClock.Time.new({
				"site1": 60
			}))

			assert(vc.currentTime.get("site1") == 60)
			vc.tick
			assert(vc.currentTime.get("site1") == 61)
		})

		it("VectorClock.Time.toJson", () => {
			var vc1 = VectorClock.new("site1", VectorClock.Time.new({
				"site1": 60,
				"site2": 273
			}))

			var timeCopy = VectorClock.Time.new(vc1.currentTime.toJson)
			assert(vc1.currentTime.equals(timeCopy))
		})

		it("VectorClock.Time.<=> and isConcurrentWith", () => {
			# Test concurrent times because they're equal
			assert(VectorClock.Time.new({
				"site1": 1,
				"site2": 0
			}).isConcurrentWith(VectorClock.Time.new({
				"site1": 1
				# site2 should implicitly be 0
			})))

			# Test concurrent times that aren't equal
			assert(VectorClock.Time.new({
				"site1": 0,
				"site2": 1
			}).isConcurrentWith(VectorClock.Time.new({
				"site1": 1,
				"site2": 0
			})))

			# Test a <=> b == 1
			assert(VectorClock.Time.new({
				"site1": 1,
				"site2": 2
			}) <=> (VectorClock.Time.new({
				"site1": 1,
				"site2": 1
			})) == 1)

			# Test a <=> b == -1
			assert(VectorClock.Time.new({
				"site1": 1,
				"site2": 1
			}) <=> (VectorClock.Time.new({
				"site1": 2,
				"site2": 1
			})) == -1)
		})

		it("VectorClock.Time.TakeMaximums", () => {
			var vc = VectorClock.Time.new({
				"site1": 1,
				"site2": 0
			})
			vc.takeMaximums(VectorClock.Time.new({
				"site1": 0,
				"site2": 1
			}))
			assert(vc.equals(VectorClock.Time.new({
				"site1": 1,
				"site2": 1
			})))
		})

		it("VectorClock.Time.equals", () => {
			# Empty times should be identical
			assert(VectorClock.Time.new({}).equals(VectorClock.Time.new({})))

			# Implicit values of 0 are ok and don't make clocks unequal
			assert(VectorClock.Time.new({
				"site1": 0
			}).equals(VectorClock.Time.new({})))

			assert(VectorClock.Time.new({
				"site1": 0,
				"site2": 1
			}).equals(VectorClock.Time.new({
				"site2": 1
			})))

			# Simple case of non-equal times
			assert(!VectorClock.Time.new({
				"site1": 1,
				"site2": 2
			}).equals(VectorClock.Time.new({
				"site2": 2
			})))

			# Concurrent times which are non-equal
			# Simple case of non-equal times
			assert(!VectorClock.Time.new({
				"site1": 1,
				"site2": 2
			}).equals(VectorClock.Time.new({
				"site1": 2,
				"site2": 1
			})))
		})
	})
}

